[env:lilygo_t_sim7080g]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
upload_flags =
    --before=no_reset
    --after=hard_reset

board_build.arduino.memory_type = qio_opi
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DTINY_GSM_MODEM_SIM7080
    -DTINY_GSM_RX_BUFFER=1024

lib_deps =
    lewisxhe/XPowersLib @ ^0.3.3
    vshymanskyy/TinyGSM @ ^0.11.7
    vshymanskyy/StreamDebugger @ ^1.0.1
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.5
    h2zero/NimBLE-Arduino @ ^1.4.3
