import { Platform } from 'react-native'

const RN_REQUIRE_MARKER = require('../assets/marker.png')

// Shared source for Marker `image` prop.
// - iOS: uses xcassets name generated by plugin (native-side cached by UIKit/GMS).
// - Android: uses drawable resource name generated by plugin.
// Fallback keeps existing JS bundled asset behavior.
export function getSharedMarkerImageSource() {
  if (Platform.OS === 'ios' || Platform.OS === 'android') {
    return { uri: 'marker_arrow_shared' } as const
  }
  return RN_REQUIRE_MARKER
}

